@startuml
class ServerController {
    - _configuration : IConfiguration
    + ServerController(configuration:IConfiguration)
    + ServerGetInfo() : IActionResult
    + ServerGetIP() : IActionResult
}
ControllerBase <|-- ServerController
@enduml
